### ISSUE TITLE
Update Solo for Network transplant process (node-overrides.yaml)

### ISSUE THREAD

**Issue by derektriley** [hiero-ledger/solo#860]
### Requested Feature

**Background**
In order for Solo to start/spin up networks with a saved state generated from a different network it will need to support placing the correct files on disk in the correct location. 

- An `override-network.json` file will be looked for by the consensus node in `NetworkAdminConfig::upgradeSysFilesLoc` (default of `data/config`).
- If the above file is not found, then the consensus node will look for a scoped override network file from a subdirectory named after the round number (for example `<NetworkAdminConfig::upgradeSysFilesLoc>/123/override-network.json`).
- The [V057RosterSchema.java](https://github.com/hashgraph/hedera-services/pull/16594/files#diff-952eb1264ac5e82c11422564f00af9d7b6e7752d30b86c954f97ee510d56482fR81) in hedera-services provides a restart-only schema which sets the appropriate active roster for genesis, override, or upgrade). It may look for the override file for the round number specified in the migration context

See this [PR](https://github.com/hashgraph/hedera-services/pull/16594) in hedera-services for more implementation details if necessary.

**Acceptance Criteria**
- Solo has been updated to support putting the `override-network.json` file(s) in the correct location for networks it spins up.
- Test to verify this process is sucessful.

**Dependencies**
- None

### Business Need

For Solo to support the network transplant process, which has been recently updated on the consensus node.

### Linked Issues
- required by: https://github.com/hiero-ledger/solo/issues/2379

**Comment by jeromy-cannon** [comment]
some additional info to help:
Per Dan: hey Jeromy — circling back to above we did get some answers, there’s some hard coded samples and then some code to generate them (albeit in python)
https://github.com/hashgraph/infrastructure/issues/7487
https://github.com/hashgraph/infrastructure/pull/7610
also a few comments in #7487 on the data format and how to generate it, in general the file is named override-network.json - i kept calling it network-override.json and nothing would work :upside_down_face: belongs in data/config

**Comment by JeffreyDallas** [comment]
@jeromy-cannon and @derektriley 

Need clarification how to get / generate `override-network.json`

I did the following test steps:
1. start a solo network and run some account create transactions
2. stop the network and save state file, and the original `genesis-network.json`

3. start a new solo network from scratch, copy state file to pod, 
4. copy `genesis-network.json` to data/config as `override-network.json`
5. start network, but failed with exeception

```
2025-08-05 14:51:33.663 1073     DEBUG STARTUP          <main> BootstrapUtils: jvmPauseDetectorThread started
2025-08-05 14:51:33.667 1074     ERROR EXCEPTION        <main> Log4jSetup: exception on thread main
java.lang.IllegalStateException: Gap in preconsensus event files detected! Previous sequence number was 1, next sequence number is 1
        at com.swirlds.platform.event.preconsensus.PcesUtilities.fileSanityChecks(PcesUtilities.java:160) ~[swirlds-platform-core-0.62.10.jar:0.62.10]
        at com.swirlds.platform.event.preconsensus.PcesFileReader.lambda$buildFileHandler$2(PcesFileReader.java:119) ~[swirlds-platform-core-0.62.10.jar:0.62.10]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
        at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395) ~[?:?]
```

So what should be correct steps and correct way to generate `override-network.json`

**Comment by jeromy-cannon** [comment]
In case we need this later:
- https://swirldslabs.slack.com/archives/C03EZRNHWSG/p1745262083153799?thread_ts=1743180130.691899&cid=C03EZRNHWSG
- https://swirldslabs.slack.com/archives/C03EZRNHWSG/p1750767882073639
- https://swirldslabs.slack.com/archives/D056R477DEJ/p1742336970027819
- https://swirldslabs.slack.com/archives/C08SW2A136K/p1749850743732479?thread_ts=1749670456.459819&cid=C08SW2A136K

**Comment by jeromy-cannon** [comment]
downgrade to P2 because initiative completion is blocked by dependency on https://github.com/hiero-ledger/hiero-block-node/issues/1513 which 'might' be scheduled for Q4 of 2026
